config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  # Rootはライブ一覧ページ

  # 基礎情報ページの表示
  get '/about', to: 'root#about'
  get '/terms', to: 'root#terms'
  get '/privacy', to: 'root#privacy'
  get '/setting', to: 'root#setting'

  #フォローしてる芸人のスケジュールを表示する
  get '/schedule', to: 'root#schedule'

  #参加予定
  get '/participate', to: 'root#participate'

  #ライブ情報検索
  get 'search', to: 'events#search'

  #Twitterログイン認証
   get 'auth/:provider/callback', to: 'sessions#create'
  #Twitterからログアウト
   get '/logout', to: 'sessions#destroy'

  #ユーザー認証
    devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # ユーザー管理
  resources :users, only: [:show, :edit, :update, :create, :destroy]

  #ライブ投稿
  resources :events, only: [:new, :create, :edit, :update, :index, :show, :destroy] do
      #参加するボタン
      resource :participates, only: [:create, :destroy]
      #検討中ボタン
      resource :pendings, only: [:create, :destroy]
      #出演者
      resource :event_performers, only: [:create, :update,:destroy]
      #リンク
      resource :event_links, only: [:create, :update,:destroy]
      #カテゴリ
      resource :event_categories, only: [:create, :update,:destroy]
      #更新履歴
      resource :event_change_histories, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pending.rb
class Pending < ApplicationRecord
	belongs_to :user
	belongs_to :event

	#1ユーザー1回まで
	validates_uniqueness_of :event_id, scope: :user_id
end

app/controllers/pendings_controller.rb
class PendingsController < ApplicationController
    def create
        event = Event.find(params[:event_id])
        pending = current_user.pendings.new(event_id: event.id)
        pending.save
        #redirect_to events_path
    end

    def destroy
        pending = current_user.pendings.find_by(event_id: params[:event_id])
        pending.destroy
        #redirect_to events_path
    end

    private

    def event_params
        params.require(:event).permit(:id, :live_date, :live_start, :live_name, :live_remarks, :link_1, :live_email, :image, :uid, :ip)
    end

    def user_params
        params.require(:user).permit(:id, :name, :profile_image, :uid, :email, :password)
    end
end

app/helpers/pending_helper.rb
module PendingHelper
end

app/views/pendings/_pending.html.erb
			<% if user_signed_in? %>
				<% if event.pending_by?(current_user) %>
				  <li>
				    <%= link_to event_pendings_path(event), method: :delete do %>
				      <i class="fas fa-question-circle" aria-hidden="true" style="color: red;"></i>
				      <%= event.pendings.count %> 検討中
				    <% end %>
				  </li>
				<% else %>
				  <li>
				    <%= link_to event_pendings_path(event), method: :post do %>
				      <i class="far fa-question-circle" aria-hidden="true"></i>
				      <%= event.pendings.count %> 検討中
				    <% end %>
				  </li>
				<% end %>
			<% else %>
			<!--ログインしていない場合、「ログインするといいね機能が使えます」のメッセージを出す-->
				<!--ログインしていない場合、「ログインするといいね機能が使えます」のメッセージを出す-->
				<%= link_to user_twitter_omniauth_authorize_path, "data-confirm" => "ログインすると参加するボタンが使えます" do %>
				      <i class="far fa-question-circle" aria-hidden="true"></i> 検討中
				<% end %>
			<% end %>

app/views/pendings/create.js.erb
$("#pending-buttons").html("<%= j(render partial: 'pendings/pending', locals: { event: event, pending: pending }) %>")

app/views/pendings/destroy.js.erb
$("#pending-buttons").html("<%= j(render partial: 'pendings/pending', locals: { event: event}) %>");