config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  # Rootはライブ一覧ページ

  # 基礎情報ページの表示
  get '/about', to: 'root#about'
  get '/terms', to: 'root#terms'
  get '/privacy', to: 'root#privacy'
  get '/setting', to: 'root#setting'

  #フォローしてる芸人のスケジュールを表示する
  get '/schedule', to: 'root#schedule'

  #参加予定
  get '/participate', to: 'root#participate'

  #ライブ情報検索
  get 'search', to: 'events#search'

  #Twitterログイン認証
   get 'auth/:provider/callback', to: 'sessions#create'
  #Twitterからログアウト
   get '/logout', to: 'sessions#destroy'

  #ユーザー認証
    devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # ユーザー管理
  resources :users, only: [:show, :edit, :update, :create, :destroy]

  #ライブ投稿
  resources :events, only: [:new, :create, :edit, :update, :index, :show, :destroy] do
      #参加するボタン
      resource :participates, only: [:create, :destroy]
      #検討中ボタン
      resource :pendings, only: [:create, :destroy]
      #出演者
      resource :event_performers, only: [:create, :update,:destroy]
      #リンク
      resource :event_links, only: [:create, :update,:destroy]
      #カテゴリ
      resource :event_categories, only: [:create, :update,:destroy]
      #更新履歴
      resource :event_change_histories, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :omniauthable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # 1Userにつき何個もライブ情報を登録できる
    has_many :events

  # 1Userにつき何個もイイねできる
    has_many :participates, dependent: :destroy

  # 1Userにつき何個も検討中に入れられる
    has_many :pendings, dependent: :destroy

  # プロフィール画像の利用
   attachment :profile_image

  # Twitter認証の場合はemailを要求しない
  # def email_required?
  #  (authentications.empty? || !email.blank?) && super
  # end

  # Twitterログイン認証
  def self.find_for_oauth(auth, signed_in_resource=nil)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
       uid:      auth.uid,
       provider: auth.provider,
       email:    User.dummy_email(auth),
       password: Devise.friendly_token[0, 20]
      )
    end
    user.skip_confirmation!
    # email仮をデータベースに保存するため、validationを一時的に無効化。
    user.save(validate: false)
    user
  end

  # 通常サインアップ時のuid用、Twitter OAuth認証時のemail用にuuidな文字列を生成
  # def self.create_unique_string
  #   SecureRandom.uuid
  # end

  # twitterではemailを取得できないので、適当に一意のemailを生成
  private
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
   end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # def twitter
    # You need to implement the method below in your model
  #  @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

  #  if @user.persisted?
  #    set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
  #    sign_in_and_redirect @user, :event => :authentication
  #  else
  #    session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
  #    redirect_to new_user_registration_url
  #  end
  #end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

    private

    def callback_from(provider)
      provider = provider.to_s

      @user = User.find_for_oauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signingdevise_parameter_sanitizer in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   .permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #def build_resource(hash=nil)
  #  hash[:uid] = User.create_unique_string
  #  super
  #end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
  end

  def destroy
    super
  end

   protected

  #If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		@user.save
	end
    def edit
        @user = User.find(params[:id])
    end
	def update
	    @user = User.find(params[:id])
	    @user.update(user_params)
	    redirect_to user_path(@user.id)
	end
	def show
	    @user = current_user

	    #　ログインユーザーが登録したライブ一覧だけ表示
   		#@events = @user.events.page(params[:page])
   		# @events = @user.events
	end

	def profile
        @user = current_user
        redirect_to user_path(@user.uid)
	end

	private
	def user_params
	    params.require(:user).permit(:id, :name, :profile_image, :uid, :email, :password)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="slice slice-lg sct-color-1">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">

            <%= form_for(@user) do |f| %>
                <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header text-center">
                        <h2 class="form-header-title">プロフィール編集</h2>
                    </div>
                    <div class="form-body">
                      <form class="mt-20">
                        <div class="form-group has-icon">
                          <label class="control-label sr-only" for="inputName"><%= f.text_field :name %></label>
                          <input type="text" class="form-control" id="inputName" placeholder="名前">
                          <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-icon">
                          <div class="user-edit-image">
                              <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                          </div>
                            <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                            <input type="file">
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-base-1 mt-20"><%= f.submit '変更を保存' %></button>
            <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/users/schedule.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
        <!--「参加中」を押したライブだけ表示-->
		 <h1>ライブ一覧</h1>
		 <% @events.participates.each do |event| %>
		    <p></p>
		    <span><%= event.live_date %></span>
		    <span><%= event.live_start %></span>
		    <span><%= link_to event.live_name, event_path(event.id) %></span>
		    <span><%= event.live_remarks %></span>
		    <span><%= event.link_1 %></span>
		 	<span><%= event.live_email %></span>
			<%= attachment_image_tag event, :image, :fill, 100, 100, format: 'jpeg' %>
			<%= link_to "編集", edit_event_path(event.id) %>
			<!--もし今のユーザーがライブを投稿したユーザーと一致したら削除ボタンを表示-->
			<% if @event.uid == current_user %>
				<%= link_to "削除", destroy_event_path(event.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
			<% end %>
			<%= paginate @events, class: "pagenate" %>
		<% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="profile-container"><br><Br><br>
    <h3 class="profile-name"><%= @user.name %></h3>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "https://pbs.twimg.com/profile_images/958803950391541760/ABdXMZLE.jpg" %>
	<% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>
    <% end %>
</div>

<%= render :partial => "events/event_list", locals: { events: @events } %>