config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  # Rootはライブ一覧ページ

  # 基礎情報ページの表示
  get '/about', to: 'root#about'
  get '/terms', to: 'root#terms'
  get '/privacy', to: 'root#privacy'
  get '/setting', to: 'root#setting'

  #フォローしてる芸人のスケジュールを表示する
  get '/schedule', to: 'root#schedule'

  #参加予定
  get '/participate', to: 'root#participate'

  #ライブ情報検索
  get 'search', to: 'events#search'

  #Twitterログイン認証
   get 'auth/:provider/callback', to: 'sessions#create'
  #Twitterからログアウト
   get '/logout', to: 'sessions#destroy'

  #ユーザー認証
    devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  # ユーザー管理
  resources :users, only: [:show, :edit, :update, :create, :destroy]

  #ライブ投稿
  resources :events, only: [:new, :create, :edit, :update, :index, :show, :destroy] do
      #参加するボタン
      resource :participates, only: [:create, :destroy]
      #検討中ボタン
      resource :pendings, only: [:create, :destroy]
      #出演者
      resource :event_performers, only: [:create, :update,:destroy]
      #リンク
      resource :event_links, only: [:create, :update,:destroy]
      #カテゴリ
      resource :event_categories, only: [:create, :update,:destroy]
      #更新履歴
      resource :event_change_histories, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	attachment :image

	#一人のユーザーが複数のライブに参加できる
    has_many :participates, dependent: :destroy

	#一人のユーザーが複数のライブを「検討中」にできる
    has_many :pendings, dependent: :destroy

  #複数のリンクを持てる
    has_many :event_links, dependent: :destroy
    accepts_nested_attributes_for :event_links, allow_destroy: true,reject_if: :all_blank
  # 子モデルの要素にもアクセスできるようにする
    #attr_accessible :event_links_attributes

  #複数の変更履歴を持てる
    has_many :event_change_histories, dependent: :destroy
    accepts_nested_attributes_for :event_change_histories, allow_destroy: true,reject_if: :all_blank
  # 子モデルの要素にもアクセスできるようにする
    #attr_accessible :event_change_histories_attributes

  #複数の出演者を持てる
    has_many :event_performers, dependent: :destroy
    accepts_nested_attributes_for :event_performers, allow_destroy: true,reject_if: :all_blank
  # 子モデルの要素にもアクセスできるようにする
    #attr_accessible :event_performers_attributes

  #複数のカテゴリを持てる
    has_many :event_categories, dependent: :destroy
    accepts_nested_attributes_for :event_categories, allow_destroy: true,reject_if: :all_blank

    #存在チェック
    validates :datetime, presence: true
    validates :title, presence: true

    #　参加するになってるかチェック
    def participated_by?(user)
      participates.where(user_id: user.id).exists?
    end

    # 検討中になってるかチェック
    def pending_by?(user)
      pendings.where(user_id: user.id).exists?
    end

    # リンクの件数をチェック
    def how_many_urls?(event)
      event_links.where(event_id: event.id).count
    end

    def user_signed_in?
         # Returns true if the user is logged in, false otherwise.
         !current_user.nil?
    end

    def self.lumine_urls
        links = []
        month = 1

        #1月〜12月分のURLを取得
        while month <= 12 do
          if month <= 9
            links << ("http://www.yoshimoto.co.jp/lumine/schedule0"+ "#{month}"+".php")
          else
            links << ("http://www.yoshimoto.co.jp/lumine/schedule"+"#{month}"+".php")
          end
          month = month + 1
        end

        links.each do |lumine_url|
            get_lumine(lumine_url)
        end
    end

    #日付検索
    ransacker :datetime, type: :date do
      Arel.sql('date(created_at)')
    end

    #ルミネのページをスクレイピング
    def self.get_lumine(link)
        lumine = Mechanize.new
        page = lumine.get(lumine_url)

        schedule_part = page.search('#schedule_pc')
        eles = schedule_part.search('ul')

        eles.each do |ele|
          if ele.search('#dayTitle').present?
            day = ele.search('#dayTitle').inner_text
          else
            day = Event.last.day
          end
          title = ele.search('li .schedule_con, .lastChild')[1].inner_text
          description = ele.search('li .schedule_con, .lastChild')[0].inner_text

          place = '¥nルミネtheよしもと¥n'
          price = ele.search('li .schedule_con, .lastChild')[4].inner_text
          performers_list = ele.search('li .schedule_con, .lastChild')[2].inner_text
          detail = ele.search('li .schedule_con, .lastChild')[3].inner_text

          remarks = place+price+"¥n"+performers_list+details

          event = Event.where(live_name: title, day: day, starting_time: starting_time, remarks: remarks).first_or_create

          #performers = performers_list.gsub(/\r\n|\s/,"").gsub(/\[.*?\]/,"／").split("／").reject(&:blank?)
          #performers.each do |name|
          #  performer = Performer.where(name: name).first_or_create
          #  live.performers << performer
          #end
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update, :edit, :destroy]

	def new
    # イベントを登録
		@event = Event.new

    # 出演者を登録
        @event.event_performers.build

    # リンクを登録
        @event.event_links.build

    # カテゴリを登録
        @event.event_categories.build

	end

	def create
        # イベント情報を取得
         @event = Event.new(event_params)

        # ipアドレスを取得
         @remote_ip = request.remote_ip

        # ログインユーザーを取得
         @user_id = current_user.id

        # DB保存→詳細画面へリダイレクト
        if @event.save
            # イベントが登録されたら、変更履歴テーブルを更新
            #@event_id = @event.id
            UpdateEventChangeHistoryService.new(@event.id,@remote_ip,@user_id).execute

            redirect_to event_path(@event.id), notice: 'ありがとうございます！ライブ登録が完了しました！'
        else
            flash.now[:error] = 'ライブ登録に失敗しました...。お手数ですが最初からやり直してください。'
            render :new
        end
    end

    def index
        @q = Event.ransack(params[:q])
    	@events = Event.page(params[:page]).includes(:event_change_histories, :event_performers, :event_links).reverse_order
    end

    def search
        @date = params[:date]
        @q = params[:q]

        #binding.pry

        #ライブ情報を日付で検索
        return @events = SearchDatetimeService.new(@date).execute if @date.present?

        #日付もしくはキーワードで検索
        return @events = SearchDatetimeKeywordService.new(params[:datetime],params[:q]).execute if params[:datetime].present? && params[:q].present?
        return @events = SearchKeywordService.new(params[:q]).execute if params[:q].present?
        return @events = SearchDatetimeService.new(params[:datetime]).execute if params[:datetime].present?

        binding.pry

        respond_to do |format|
          format.html # index.html.erb
        end
    end

    def show
    end

    def edit
    end

    def update
        # ipアドレスを取得
         @remote_ip = request.remote_ip

        # ログインユーザーを取得
         @user_id = current_user.id

        # エラーチェック＆DB保存→詳細画面へリダイレクト
        if @event.update(event_params)
            # イベントが編集されたら、変更履歴テーブルを更新
            @event_id = @event.id
            UpdateEventChangeHistoryService.new(@event.id,@remote_ip,@user_id).execute

            redirect_to event_path(params[:id]) , notice: 'ありがとうございます！ライブ登録が完了しました！'
        else
            flash.now[:error] = 'ライブ編集に失敗しました...。お手数ですが最初からやり直してください。'
            render :edit
        end
    end

    def destroy
        @event.destroy
        redirect_to events_path
    end

	private
    #ライブ情報
    def event_params
        params.require(:event)
        .permit(
            :id,
            :datetime,
            :title,
            :description,
            :tel,
            :email,
            :image,
            event_links_attributes: [
                :id,
                :event_id,
                :url],
            event_change_histories_attributes: [
                :id,
                :event_id,
                :user_id,
                :user_ip],
            event_performers_attributes: [
                :id,
                :event_id,
                :performer],
            event_categories_attributes: [
                :id,
                :event_id,
                :category]
        )
    end

    #ユーザー情報
    def user_params
        params.require(:user).permit(:id, :name, :profile_image, :uid, :email, :password)
    end

    #検索クエリ
    def search_params
        params.require(:q).permit(:title_or_description_or_event_performers)
        params.require(:keyword).permit(:title_or_description)
        params.require(:date).permit(:datetime_eq)
        params.require(:date_and_keyword).permit
    end

    def set_event
        @event = Event.find_by(id: params[:id])
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_list.html.erb
<main class="content">
    <div class="snackbar"><span><h2>ライブ一覧</h2></span></div>
  <div class="lp-timeline">
    <div class="lp-timeline-wrap">
	   <% @events.each do |event| %>
      <article class="post element hard-shadows">
          <div class="post-header post-header-s1 post-date-1">
              <div class="post-icon">
                  <span class="icon-permalink"></span>
              </div>
              <span class="date-format date-format-1">
              <font size="3">
              <% wd = ["日", "月", "火", "水", "木", "金", "土"] %>
              <span><%= event.datetime.strftime('%Y年%m月%d日 %H:%M') %></span>
              <div class="post-counts">
                <span class="share-button"></span>
                <div class="share-option hidden" onClick="window.open('http://twitter.com/share?text=wArally%21&url=https://tmblr.co/ZB3_lc2Tyk2Mu', 'twitter_share', 'height=320, width=640, toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, directories=no, status=no');">
                    Twitter
                </div>
                <div class="share-option hidden" onClick="window.open('https://plus.google.com/share?url=https://tmblr.co/ZB3_lc2Tyk2Mu', 'google_plus_share', 'height=320, width=500, toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, directories=no, status=no');">
                    LINE
                </div>
                <div class="share-option hidden" onClick="window.open('http://www.facebook.com/sharer/sharer.php?u=https://tmblr.co/ZB3_lc2Tyk2Mu&t=wArally%21', 'facebook_share', 'height=320, width=640, toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, directories=no, status=no');">
                    Facebook
                </div>
              </div>

        <div class="post-wrapper">
          <div class="post-box">
                                <h3 class="post-title">
                                  <%= link_to event.title, event_path(event.id) %>
                                </h3>
                            </div>
                            <div class="post-text typography">
	                                <p><%= event.description %></p>
								    <span><%= event.tel %></span>
								 	<span><%= event.email %></span>
								 	<!-- 出演者を表示 -->
								 	  <% event.event_performers.each do |performer| %>
									    <%= performer.performer %>
									  <% end %>
									<!-- URLを表示 -->
								 	  <% event.event_links.each do |link| %>
									    <%= link.url %>
									  <% end %>
									<!-- カテゴリを表示 -->
								 	  <% event.event_categories.each do |category| %>
									    <%= category.category %>
									  <% end %>
                            </div>
                            <%= attachment_image_tag event, :image, :fill, 100, 100, format: 'jpeg' %>
                      <div class="post-text typography">
                          <div class="post-options">
                            <div class="edit-box">
                              <div class="edit-button">
                              <i class="fas fa-edit" style="font-size:15px; color:#FFFFFF;text-align:right;"　aria-hidden="true"></i>
                              <%= link_to "編集", edit_event_path(event.id) %>
                              </div>
                            </div>
                            <div class="like-button">
                                <div id="participate-bottun">
                                <%= render :partial => "participates/participate", locals: { event: event } %>
                                </div>
                            </div>
                            <div class="pending-button">
                              <div class ="pending-button">
                                <%= render :partial => "pendings/pending", locals: { event: event } %>
                              </div>
                            </div>
                            <div class="link-button">
                              <div class="link-button">
                                <%= render :partial => "events/link", locals: { event: event } %>
                              <div>
                            </div>
                        </div>
                    </div>
                </article>
		<% end %>
		<%= paginate @events, class: "pagenate" %>

app/views/events/_link.html.erb
	<% if event.email.present? %>
		<i class="fas fa-envelope"></i>
		<%= mail_to(event.email, name = current_user.name, '予約する') %>
	<% elsif event.tel.present? %>
		<i class="fas fa-phone"></i>
		<%= link_to '予約する','tel:'+event.tel %>
	<% end %>

app/views/events/_link2.html.erb
<% if %>
	<% if event.email.present? %>
		<i class="fas fa-envelope"></i>
		<%= mail_to(event.email, name = current_user.name, '予約する') %>
	<% elsif event.tel.present? %>
		<i class="fas fa-phone"></i>
		<%= link_to('予約する', 'tel:'+event.tel) %>
	<% elsif event.how_many_urls? > 0 %>
		<% @events.links.each do |link| %>
			<% if events.how_many_urls?(link) == 1 %>
				<i class="fas fa-ticket-alt" data-fa-transform="rotate-30 up-1" style="font-size:15px; color:#FFFFFF;text-align:right;"　aria-hidden="true"></i>
				<%= link_to '予約する', link.url %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/events/_participate.html.erb
			<% if user_signed_in? %>
				<% if @event.participated_by?(current_user) %>
				  <li>
				    <%= link_to event_participates_path(@event), method: :delete, id: "participate-button", remote: true do %>
				      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				      <%= @event.participates.count %> 参加する
				    <% end %>
				  </li>
				<% else %>
				  <li>
				    <%= link_to event_participates_path(@event), method: :post, id: "participate-button", remote: true do %>
				      <i class="fa fa-heart-o" aria-hidden="true"></i>
				      <%= @event.participates.count %> 参加する
				    <% end %>
				  </li>
				<% end %>
			<% else %>
			<% end %>

app/views/events/_search_form.html.erb
    日付から探す<br>
    <span><%= link_to '明日', search_path(:date => 'today') %></span>
    <span><%= link_to '明日', search_path(:date => 'tomorrow') %></span>
    <span><%= link_to '次の土曜', search_path(:date => 'next_sat') %></span>
    <span><%= link_to '次の日曜', search_path(:date => 'next_sun') %></span><br>
    <span>
	日付を指定する
   	<%= form_tag(search_path, method: "get") do %>
			  <%= datetime_select(:event, :datetime) %>
			  <%= submit_tag("検索") %>
	<% end %></span>
    キーワードで探す<br>
	<%= form_tag(search_path, method: "get") do %>
	  <%= text_field_tag(:q) %>
	  <%= submit_tag("検索") %>
	<% end %>
</span>

app/views/events/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@event) do |f| %>
    <h4>開催日時</h4>
    <%= f.datetime_select :datetime %></span>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :descripition %>
	<%= f.text_field :tel %>
	<%= f.text_field :email %>
    <h4>画像</h4>
	<%= f.attachment_field :image %>
    <%= f.submit '保存' %>
<% end %>

app/views/events/index.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
		<% if flash[:notice] %>
		  <p><%= flash[:notice] %></p>
		<% end %>
			<div class="lp">
			  <div class="lp-intro">
			    <div class="inner">
			      <div class="lp-intro-hero">
			        <p class="lp-intro-hero-text">おもしろい！を見つけよう</p>
              <%= render :partial => "events/search_form", locals: { q: @q } %>
			      </div>
			    </div>
			  </div>
      </div>
      <%= render :partial => "events/event_list", locals: { events: @events } %>
      <%= link_to Date.today.prev_day, search_path(date: 'prev_day') %>
      <%= link_to Date.today.next_day, search_path(date: 'next_day') %>
			<%= paginate @events, class: "pagenate" %>
      </div>
    </div>
  <div class="lp-panel">
    <div class="inner">
      <div class="lp-panel-item">
        <div class="lp-panel-item-image" style="background-image: url()"></div>
        <div class="lp-panel-item-body">
          <h2 class="lp-panel-item-title">気になるライブを見つけよう</h2>
          <p class="lp-panel-item-text">都内で毎日30〜40件行われているお笑いライブを、<strong>日付</strong>または<strong>キーワード</strong>で横断検索できます。</p>
        </div>
      </div>
      <div class="lp-panel-item">
        <div class="lp-panel-item-image" style="background-image: url()"></div>
        <div class="lp-panel-item-body">
          <h2 class="lp-panel-item-title">ライブ情報を登録・編集する</h2>
          <p class="lp-panel-item-text">ライブの情報は<strong>誰でも</strong>登録・編集が可能です。好きな芸人さんのファン同士で情報をシェアしましょう！ライブ主催者の方のご登録も大歓迎です。</p>
        </div>
      </div>
      <div class="lp-panel-item">
        <div class="lp-panel-item-image" style="background-image: url()"></div>
        <div class="lp-panel-item-body">
          <h2 class="lp-panel-item-title">ライブの参加予定を管理する</h2>
          <p class="lp-panel-item-text">自分が気になるライブを<strong>「参加する」</strong>または<strong>「検討中」</strong>のボタンを押してブックマークできます。</p>
        </div>
      </div>
      <div class="lp-panel-item">
        <div class="lp-panel-item-image" style="background-image: url()"></div>
        <div class="lp-panel-item-body">
          <h2 class="lp-panel-item-title">好きな芸人さんをフォローする</h2>
          <p class="lp-panel-item-text">自分が好きな芸人さんを<strong>「フォロー」</strong>することで、フォローした芸人さんが出るライブの情報だけをタイムライン上に表示させることが可能です。</p>
        </div>
      </div>
    </div>
  </div>

  <div class="lp-footer">
    <div class="inner">
      <div class="logo">wArally!</div>
      <p>ログインするとwArally!のすべての機能をご利用いただけます！</p>
        <a class="button twitter-button-large" href="/auth/twitter">
          <i class="fab fa-twitter"></i> さっそく使い始める
        </a>
  </div>
</div>
</main>
</div>
</section>

app/views/events/new.html.erb
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/redmond/jquery-ui.css" >

<br><br><br><br><br>
<article class="">
    <div class="">
        <div class="">
            <span class=""></span>
        </div>
    </div>
    <div class="post-wrapper">
        <h1 class="post-title">ライブ登録</h1>
        <div class="post-box">
        <%= form_for(@event) do |f| %>

            <input type="text" data-type="date" id="date-input" />
            <div id="material-header-holder" style="display:none">
              <div class="ui-datepicker-material-header">
                <div class="ui-datepicker-material-day">
                </div>
                <div class="ui-datepicker-material-date">
                  <div class="ui-datepicker-material-month">
                  </div>
                  <div class="ui-datepicker-material-day-num">
                  </div>
                  <div class="ui-datepicker-material-year">
                  </div>
                </div>
              </div>
            </div>

            <h4>開催日時</h4>
            <%= f.datetime_select :datetime %><br>

            <%= f.text_field :title,:placeholder => "タイトル" %><br>
            <%= f.text_area :description,:placeholder => "内容" %><br>
            <%= f.text_field :email,:placeholder => "メールアドレス"  %><br>
            <%= f.text_field :tel,:placeholder => "電話番号"  %><br>

            <%= f.fields_for :event_links do |urls_form| %>
                <%= urls_form.text_field :url,:placeholder => "予約URL"  %><br>
            <% end %>

            <%= f.fields_for :event_performers do |performers_form| %>
                <%= performers_form.text_area :performer,:placeholder => "出演者"  %><br>
            <% end %>

            <%= f.fields_for :event_categories do |categories_form| %>
                <%= categories_form.text_field :category,:placeholder => "カテゴリ"  %><br>
            <% end %>

            <h4>画像</h4>
            <%= f.attachment_field :image %>

            <%= f.submit 'ライブ登録' %>

        <% end %>
        </div>
    </div>
</article>

app/views/events/search.html.erb
<br><br><br><br>
<%= render :partial => "events/event_list", locals: { events: @events } %>

app/views/events/show.html.erb
<section class="single-blog">
	<h2 class="blog-headline">ライブ詳細</h2>
  <article>
    <div class="post-card-wrap">
      <h3 class="post-card-title"><%= @event.title %></h3>
      <div class="post-card-text"><p><%= @event.description %></p>
      <span><%= @event.id %></span>
        <%= @event.datetime.strftime('%Y年%m月%d日 %H:%M') %></span>
        <span><%= @event.tel %></span>
      <span><%= @event.email %></span>
      <%= attachment_image_tag @event, :image, :fill, 100, 100, format: 'jpeg' %>

      <%= render :partial => "participates/participate", locals: { event: @event } %>
      <%= render :partial => "pendings/pending", locals: { event: @event } %>
      </a>
    </li>
		</div>
</section>